name: Build
on:
  push:
    branches:
      - master
      - alpha
      - beta
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn test

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npx semantic-release
        if: matrix.node-version == '14.x'
        env:
          GH_TOKEN: secrets.GITHUB_TOKEN
          NPM_TOKEN: secrets.NPM_TOKEN
